from app.models.report_schema import ProjectInput, ReportOutput, RiskItem


def generate_report(project: ProjectInput) -> ReportOutput:
    risks = [
        RiskItem(
            area="Project Structure",
            level="Medium",
            notes="Project documentation is limited at this stage."
        ),
        RiskItem(
            area="Market Maturity",
            level="Low",
            notes="The project operates in a highly competitive sector."
        )
    ]

    return ReportOutput(
        project_name=project.name,
        overall_risk="Medium",
        risks=risks,
        summary="This is an initial automated risk assessment generated by BlockSentinel."
    )
